# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-28 07:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0004_usematerial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usematerial',
            old_name='usematerial_name',
            new_name='material_name',
        ),
    ]
