# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-28 08:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0005_auto_20200228_1048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usematerial',
            old_name='material_name',
            new_name='material',
        ),
    ]
