# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-28 11:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_type',
            old_name='is_manager',
            new_name='is_store',
        ),
    ]
